ERRORDEFINE(iRRAM_overflow_error,          "iRRAM_overflow_error")
ERRORDEFINE(iRRAM_underflow_error,         "iRRAM_underflow_error")
ERRORDEFINE(iRRAM_integer_error,           "iRRAM_integer_error")
ERRORDEFINE(iRRAM_interval_divide_by_zero, "iRRAM_interval_divide_by_zero")
ERRORDEFINE(iRRAM_cacheerror_test,         "iRRAM_cacheerror_test")
ERRORDEFINE(iRRAM_cacheerror_rkonvert,     "iRRAM_cacheerror_rkonvert")
ERRORDEFINE(iRRAM_cacheerror_skonvert,     "iRRAM_cacheerror_skonvert")
ERRORDEFINE(iRRAM_cacheerror_ikonvert,     "iRRAM_cacheerror_ikonvert")
ERRORDEFINE(iRRAM_conversion_from_infinite,"iRRAM_conversion_from_infinite")
ERRORDEFINE(iRRAM_general_divide_by_zero,  "iRRAM_general_divide_by_zero")
